apiVersion: v1
kind: Service
metadata:
  name: breast-cancer-api-service
  labels:
    app: breast-cancer-api
spec:
  type: NodePort
  selector:
    app: breast-cancer-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 30800
